const { sushi } = require('./sushi');

const { AssignmentRule } = sushi.fshrules;
const { FshCode } = sushi.fshtypes;

function assignmentRule(pathValue, value) {
  const rule = new AssignmentRule(pathValue);
  rule.value = value;
  return rule;
}

function codeAssignmentRule(pathValue, code) {
  return assignmentRule(pathValue, new FshCode(code));
}

function addAssignment(ruleSet, pathValue, value) {
  ruleSet.rules.push(assignmentRule(pathValue, value));
}

function addCodeAssignment(ruleSet, pathValue, code) {
  ruleSet.rules.push(codeAssignmentRule(pathValue, code));
}

function ruleSetToFsh(ruleSet) {
  return [`RuleSet: ${ruleSet.name}`, ...ruleSet.rules.map(rule => rule.toFSH())].join('\n');
}

// Keep generated FSH headers consistent and explicit about their source inputs.
function generatedFshFile({ scriptName, inputPaths = [], content }) {
  return `${[
    `// This file is generated by scripts/${scriptName}.`,
    '// Do not edit by hand; update source inputs and rerun the script.',
    ...inputPaths.map(inputPath => `// Source input: ${inputPath}`),
    '// See scripts/README.md for developer documentation.',
    '',
    content
  ]
    .join('\n')
    .trimEnd()}\n`;
}

module.exports = {
  addAssignment,
  addCodeAssignment,
  assignmentRule,
  codeAssignmentRule,
  generatedFshFile,
  ruleSetToFsh
};
